# Generated by Django 5.2.14 on 2026-05-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_trip_options_trip_cover_photo_trip_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='privacy',
            field=models.CharField(default='private', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='saved_destinations',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
